INSERT INTO doctores(
            cop, nom_doc, ape_doc, esp_doc, uni_doc, hab_doc)
    VALUES ('7310-RNE0027', 'GUSTAVO RAMIRO', 'ROJAS MANRIQUE', 'ORTODONCIA Y ORTOPEDIA MAXILO FACIAL', 'UNIVERSIDAD PERUANA CAYETANO HEREDIA', '1'),
     ('7310-RNE0027', 'GUSTAVO RAMIRO', 'ROJAS MANRIQUE', 'RADIOLOGIA ORAL Y MAXILO FACIAL', 'UNIVERSIDAD PERUANA CAYETANO HEREDIA', '1'),
     ('13854', 'ROBERTO SANDRO', 'MAMANI FLORES', 'PERIODONCIA E IMPLANTACION', 'UNIVERSIDAD DE SAO PAULO BRASIL', '1'),
     ('13446', 'DAVID MANUEL', 'MORA VALDIVIA', 'ORTODONCIA Y ORTOPEDIA MAXILO FACIAL', 'UNIVERSIDAD CATOLICA SANTA MARIA', '1'),
     ('19463', 'MARIELA IVONNE', 'GARATE VILLASANTE', 'ODONTOPEDIATRIA', 'UNIVERSIDAD CATOLICA SANTA MARIA', '1'),
     ('17092', 'PAUL JORGE', 'VALDIVIA GAMERO', 'ENDODONCIA', 'UNIVERSIDAD DE SAO PAULO BRASIL', '1'),
     ('15179', 'HECTOR ELIAS', 'GONZALES BERNAL', 'ESTETICA DENTAL', 'UNIVERSIDAD DE SAO PAULO BRASIL', '1'),
     ('3100', 'CESAR JORGE', 'VALDIVIA GORDILLO', 'CIRUGIA DE CABEZA CUELLO Y MAXILO FACIAL', 'UNIVERSIDAD CATOLICA SANTA MARIA', '1'),
     ('23744', 'MIRIAN EVELYN', 'CHAVEZ CALATAYUD', 'CIRUJANO DENTISTA', 'UNIVERSIDAD ALAS PERUANAS', '1'),
     ('7753', 'LEONCIO ARTURO', 'MENENDEZ LINAREZ', 'REHABILITACION ORAL', 'UNIVERSIDAD PERUANA CAYETANO HEREDIA', '1'),
     ('15321', 'JOSE SANTIAGO', 'GAMERO QUINTANILLA', 'CIRUJANO DENTISTA', 'UNIVERSIDAD CATOLICA SANTA MARIA', '1'),
     ('20696', 'ANGELA FIORELLA', 'CALIENES RODRIGUEZ', 'IMPLANTES', 'CPO-UNINGA PROFISSOES DA SAUDE', '1'),
     ('18361', 'ROBERTO MELVIN', 'CANAHUA CONDORI', 'ORTODONCIA', 'UNIVERSIDAD NACIONAL DEL ALTIPLANO', '1');
